### ISSUE TITLE
Cannot disable anchors in a specific page.

### ISSUE THREAD

**Issue by RojerGS** [getgrav/grav-plugin-anchors#24]
I cannot disable anchorjs in my custom error 404 page.

You can find the exact page setup I'm using here: [https://github.com/RojerGS/mathspp/tree/master/pages/error](https://github.com/RojerGS/mathspp/tree/master/pages/error).
And you can test it by accessing a random route in my website, e.g. [https://mathspp.com/agadfasdfasdfaff](https://mathspp.com/agadfasdfasdfaff).

My `frontmatter.yaml` looks like this:

```
anchors:
    active: false
    enabled: false
metadata:
    author: Rodrigo Girão Serrão
routable: false
```

But for some reason, the anchor to the h1 title is there.
